name: Push Event
on:
  push:
    branches: [dev]
  # pull_request:
  # branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
          architecture: "x64"
        continue-on-error: false
      - run: beta/test_000_main.py
